let getEnv = {
  Port: process.env.PORT || 5000,
  MONGO_URL: process.env.MONGO_URL || "",
  SMTP_HOST: process.env.SMTP_HOST || "",
  SMTP_PORT: process.env.SMTP_PORT || 587,
  SMTP_PASS: process.env.SMTP_PASS || "",
  SMTP_USER: process.env.SMTP_USER || "",
  EMAIL_FROM: process.env.EMAIL_FROM || "",
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET || "",
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || "",
  APP_URL: `${process.env.APP_URL}:${process.env.PORT || 5000}`,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || "",
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || "",
  GOOGLE_REDIRECT_URL: process.env.GOOGLE_REDIRECT_URL,
  CLOUDINARY_SECRET: process.env.CLOUDINARY_SECRET || "",
  CLOUDINAEY_API_KEY: process.env.CLOUDINARY_APIKEY || "",
  CLOUDNAME: process.env.CLOUDNAME || "",
  REDIS_URL: process.env.REDIS_URL || "",
};
export default getEnv;
